### ISSUE TITLE
Meta viewport is not same as mentioned version by bootstrap.

### ISSUE THREAD

**Issue by dehghani-mehdi** [joshbuchea/HEAD#250]
Hi,

Your version of meta viewport (`<meta name="viewport" content="width=device-width, initial-scale=1">`) is not same as mentioned version in [bootstrap docs](https://getbootstrap.com/docs/4.4/getting-started/introduction/#starter-template) (`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`).

I'm wondering which one is better option?

**Comment by willpower232** [comment]
see https://github.com/joshbuchea/HEAD/issues/198

**Comment by joshbuchea** [comment]
Thanks @willpower232

@dehghani-mehdi if you read the discussion in #198 we opted to remove it because:

> `shrink-to-fit=no` became irrelevant during the iOS 9.3 lifecyle and beyond

I am curious to know why it's still included in the Bootstrap docs, because it looks there was a [discussion](https://github.com/twbs/bootstrap/issues/27861) and ultimately it was [removed from the project](https://github.com/twbs/bootstrap/pull/28314/files).

I tried poking around for the current `4.4` docs, but didn't find them in the few minutes I spent searching. The latest version of docs in the [bootstrap repo](https://github.com/twbs/bootstrap/) is `4.3`. If anyone can find the current docs, we can open up a PR.

**Comment by dehghani-mehdi** [comment]
In [v4-dev branch](https://github.com/twbs/bootstrap/edit/v4-dev/site/docs/4.4/getting-started/introduction.md), the `viewport` still is same as website. I don't know if it is the right file or not tho.

**Comment by joshbuchea** [comment]
@dehghani-mehdi I'm not 100%, but that looks like the correct branch 👍

This is a good opportunity for someone to open a PR on the [bootstrap repo](https://github.com/twbs/bootstrap/). If no one gets around to it after a bit, I'll probably open up a PR when I have some free time.

**Comment by dehghani-mehdi** [comment]
[Done](https://github.com/twbs/bootstrap/pull/30331)

**Comment by dehghani-mehdi** [comment]
@joshbuchea [Done](https://github.com/twbs/bootstrap/pull/30332)

**Comment by XhmikosR** [comment]
v4-dev branch supported and supports those old iOS devices.

**Comment by dehghani-mehdi** [comment]
Bootstrap team removed `shrink-to-fit=no` part in their v5's doc, so no need to do anything for this issue anymore.
