### ISSUE TITLE
http-equiv

### ISSUE THREAD

**Issue by artemgurzhii** [joshbuchea/HEAD#52]
`<meta http-equiv="Content-language" content="en-GB"> `
Specifying the document language. It can be used by search engines when indexing pages.
`<meta http-equiv="Content-type" content="text/html>`
Specify the type of document.
Both of them used by some search engines.

**Comment by BlackSkorpio** [comment]
This is depreciated in HTML5

> "Because of the history of confusion and inconsistent implementation surrounding this kind of declaration, in 2011 the HTML Working Group took a decision to make the meta element with http-equiv set to Content-Language non-conforming in HTML. This means that you should no longer use it in HTML5, and therefore, though technically not illegal in other types of HTML, it is best to now not use it anywhere."
https://www.w3.org/International/questions/qa-http-and-lang

Instead you are recommended to use `<html lang="en">`

**Comment by artemgurzhii** [comment]
@BlackSkorpio didn't know that. what about Content-type?

**Comment by BlackSkorpio** [comment]
@artemgurzhii You can use both `<meta charset="utf-8" />` and `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` In HTML5, they are equivalent. 
Use the shorter one `<meta charset="utf-8" />`, it is easier to remember and type. [Browser support is fine](http://code.google.com/p/doctype-mirror/wiki/MetaCharsetAttribute) since it was designed for backwards compatibility.

**Comment by artemgurzhii** [comment]
@BlackSkorpio ok, thanks)
