### ISSUE TITLE
Unlicense

### ISSUE THREAD

**Issue by dcondrey** [joshbuchea/HEAD#93]
Recommend changing licensing to http://unlicense.org/ since this is merely a reference list.

**Comment by vonrac** [comment]
Another solution is [CC0](https://creativecommons.org/about/cc0/). I've known CC for years but only found out about Unlicense now.

**Comment by joshbuchea** [comment]
Great suggestions! Thanks @dcondrey & @vonrac!

**Comment by dodekeract** [comment]
@joshbuchea while I don't think anybody will file a claim (or that it's even possible), beware that you can't just change the LICENSE if you have random contributors, since they didn't agree on giving you their work for publishing under a different license. In the future I'd suggest you to avoid doing that or letting people agree to a "collaboration policy" before accepting pull requests.

**Comment by joshbuchea** [comment]
@dodekeract thanks for pointing this out! This is my first experience maintaining a popular project and accepting pull requests from so many contributors. In the future I will avoid changing the license on a project after accepting contributions from others.

Any other advice is welcome. Thank you.
